version: '3'
services:
  rackhost_dns_update:
    image: rackhost_dns_update
    container_name: rackhost_dns_update
    platform: linux/arm64
    build:
      dockerfile: Dockerfile
      context: ./src
    ports:
      - "8245:80"
    restart: always
    env_file:
      - ./src/.env